; Definition of the ucode.

#once

#bankdef mrom
{
    bits = 16
    outp = 0
    size = 255
    fill = 0
}

#bankdef acpu
{
  bits = 32
  outp = 16*256
  addr = 0x0000
}

; BUS CONTROL
BUS_READ_OFFSET = 0 ; offset of bus control signals 
BUS_READ_SEL_LEN = 3
SIG_BUS_READ_SEL_PC   = 0 << BUS_READ_OFFSET  ; PC from bus
SIG_BUS_READ_SEL_MAR  = 1 << BUS_READ_OFFSET  ; MAR from bus
SIG_BUS_READ_SEL_MDR = 2 << BUS_READ_OFFSET  ; MDR from bus
SIG_BUS_READ_SEL_IR   = 3 << BUS_READ_OFFSET  ; IR from bus
SIG_BUS_READ_SEL_ACC  = 4 << BUS_READ_OFFSET  ; ACC from bus
SIG_BUS_READ_SEL_FLAGS  = 5 << BUS_READ_OFFSET  ; FLAGS from bus
BUS_READ_END = BUS_READ_OFFSET + BUS_READ_SEL_LEN

BUS_WRITE_OFFSET = BUS_READ_END
BUS_WRITE_SEL_LEN = 4
SIG_BUS_WRITE_SEL_PC  = 0 << BUS_WRITE_OFFSET ; PC to bus
SIG_BUS_WRITE_SEL_MAR  = 1 << BUS_WRITE_OFFSET ; MAR from bus
SIG_BUS_WRITE_SEL_MDR = 2 << BUS_WRITE_OFFSET ; MDR to bus
SIG_BUS_WRITE_SEL_IR_IMM8 = 3 << BUS_WRITE_OFFSET ; IR from bus
SIG_BUS_WRITE_SEL_ACC  = 4 << BUS_WRITE_OFFSET ; ACC to bus
SIG_BUS_WRITE_SEL_ALU  = 5 << BUS_WRITE_OFFSET ; ALU to bus
SIG_BUS_WRITE_SEL_FLAGS  = 6 << BUS_WRITE_OFFSET  ; FLAGS from bus
SIG_BUS_WRITE_SEL_CONST_ADDR_VEC  = 7 << BUS_WRITE_OFFSET ; const 0x0002 to bus
SIG_BUS_WRITE_SEL_CONST_ADDR_ISR  = 8 << BUS_WRITE_OFFSET ; const 0x0003 to bus
SIG_BUS_ACCESS_EN = 1 << BUS_WRITE_OFFSET + BUS_WRITE_SEL_LEN
BUS_WRITE_END = BUS_WRITE_OFFSET + BUS_WRITE_SEL_LEN + 1

; uPC CONTOL
UPC_OFFSET = BUS_WRITE_END
SIG_UPC_RESET = 1 <<  UPC_OFFSET + 0
SIG_UPC_FROM_mROM = 1 << UPC_OFFSET +1
UPC_END = UPC_OFFSET + 2

; PC CONTROL
PC_OFFSET = UPC_END
SIG_PC_INC  = 1 << PC_OFFSET + 0 ; PC increment
SIG_PC_ADD_OFFSET  = 1 << PC_OFFSET + 1 ; PC increment
PC_END = PC_OFFSET + 2



; RAM CONTROL 
; (layered with ALU CONTROL, MUXed by SIG_BUS_WRITE_SEL_ALU (set -> alu_sel, cleared -> ram_ctrl)
RAM_OFFSET = PC_END ; offset of ram control signals
SIG_RAM_READ = 1 << RAM_OFFSET + 0 ; read from RAM (to MDR)
SIG_RAM_WRITE = 1 << RAM_OFFSET + 1 ; write to RAM (from MDR)
RAM_END = RAM_OFFSET + 2

; ALU CONTROL
ALU_OFFSET = RAM_OFFSET
ALU_OP_SEL_LEN = 3
SIG_ALU_OP_ADC = 0 << ALU_OFFSET  ; ALU: A + B [A <- ACC, B <- MDR]
SIG_ALU_OP_SBB = 1 << ALU_OFFSET  ; ALU: A - B [A <- ACC, B <- MDR]
SIG_ALU_OP_SHL = 2 << ALU_OFFSET  ; ALU: A << B [A <- ACC, B <- MDR]
SIG_ALU_OP_SHR = 3 << ALU_OFFSET  ; ALU: A >> B [A <- ACC, B <- MDR]
SIG_ALU_OP_AND = 4 << ALU_OFFSET  ; ALU: A & B [A <- ACC, B <- MDR]
SIG_ALU_OP_OR  = 5 << ALU_OFFSET  ; ALU: A | B [A <- ACC, B <- MDR]
SIG_ALU_OP_XOR = 6 << ALU_OFFSET  ; ALU: A ^ B [A <- ACC, B <- MDR]
SIG_ALU_CARRY_0 = 0b00 << ALU_OFFSET + ALU_OP_SEL_LEN + 0  ; ALU[Carry_in] = 0
SIG_ALU_CARRY_1 = 0b01 << ALU_OFFSET + ALU_OP_SEL_LEN + 0  ; ALU[Carry_in] = 1
SIG_ALU_CARRY_FLAG = 0b10 << ALU_OFFSET + ALU_OP_SEL_LEN + 0  ; ALU[Carry_in] = FLAG[CARRY]
ALU_END = ALU_OFFSET + ALU_OP_SEL_LEN + 2

; FLAGS CONTROL
FLAGS_OFFSET = ALU_END
SIG_FLAGS_CLEAR  = 1 << FLAGS_OFFSET + 0   ; signals CPU to clear flags
SIG_FLAGS_UPDATE = 1 << FLAGS_OFFSET + 1   ; signals CPU to update alu flags according to data on bus
SIG_FLAG_CHANGE  = 1 << FLAGS_OFFSET + 2   ; signals CPU to update a single flag
SIG_FLAG_VALUE   = 0 << FLAGS_OFFSET + 3   ; the value to update to, will be determined later
FLAG_SEL_OFFSET  =      FLAGS_OFFSET + 4
FLAG_SEL_LEN = 2
SIG_FLAG_SEL_HALT  = 0 << FLAG_SEL_OFFSET
SIG_FLAG_SEL_IE    = 1 << FLAG_SEL_OFFSET
SIG_FLAG_SEL_CARRY = 2 << FLAG_SEL_OFFSET
SIG_FLAG_SEL_ZERO  = 3 << FLAG_SEL_OFFSET
FLAGS_END = FLAG_SEL_OFFSET + FLAG_SEL_LEN

; EXECUTION CONTROL
EXEC_SEL_LEN = 3
EXEC_OFFSET = FLAGS_END
SIG_EXEC_SEL_ALWAYS = 0 << EXEC_OFFSET ; execute always
SIG_EXEC_SEL_CARRY  = 1 << EXEC_OFFSET ; execute, if carry is set
SIG_EXEC_SEL_ZERO   = 2 << EXEC_OFFSET ; execute, if zero is set
SIG_EXEC_SEL_NEG    = 7 << EXEC_OFFSET ; execute, if neg(ative) is set
SIG_EXEC_SEL_ZERO_NOBORROW   = 3 << EXEC_OFFSET ; execute, if zero is set
SIG_EXEC_INV        = 1 << EXEC_OFFSET + EXEC_SEL_LEN
EXEC_END = EXEC_OFFSET + EXEC_SEL_LEN + 1



#fn set_flag(flag,value) => SIG_FLAG_CHANGE | {flag} | {value} << (FLAG_SEL_OFFSET-1)

; ucode definition

#ruledef ucode
{
    uc {signals} => signals`32
}


;; helper
SIG_PC_IN    = SIG_BUS_ACCESS_EN | SIG_BUS_READ_SEL_PC
SIG_MAR_IN   = SIG_BUS_ACCESS_EN | SIG_BUS_READ_SEL_MAR
SIG_MDR_IN   = SIG_BUS_ACCESS_EN | SIG_BUS_READ_SEL_MDR
SIG_IR_IN    = SIG_BUS_ACCESS_EN | SIG_BUS_READ_SEL_IR
SIG_ACC_IN   = SIG_BUS_ACCESS_EN | SIG_BUS_READ_SEL_ACC
SIG_FLAGS_IN = SIG_BUS_ACCESS_EN | SIG_BUS_READ_SEL_FLAGS

SIG_PC_OUT   = SIG_BUS_ACCESS_EN | SIG_BUS_WRITE_SEL_PC
SIG_MAR_OUT   = SIG_BUS_ACCESS_EN | SIG_BUS_WRITE_SEL_MAR
SIG_MDR_OUT   = SIG_BUS_ACCESS_EN | SIG_BUS_WRITE_SEL_MDR
SIG_IR_IMM8_OUT = SIG_BUS_ACCESS_EN | SIG_BUS_WRITE_SEL_IR_IMM8
SIG_ACC_OUT   = SIG_BUS_ACCESS_EN | SIG_BUS_WRITE_SEL_ACC
SIG_ALU_OUT   = SIG_BUS_ACCESS_EN | SIG_BUS_WRITE_SEL_ALU
SIG_FLAGS_OUT = SIG_BUS_ACCESS_EN | SIG_BUS_WRITE_SEL_FLAGS
SIG_CONST_ADDR_VEC_OUT = SIG_BUS_ACCESS_EN | SIG_BUS_WRITE_SEL_CONST_ADDR_VEC
SIG_CONST_ADDR_ISR_OUT = SIG_BUS_ACCESS_EN | SIG_BUS_WRITE_SEL_CONST_ADDR_ISR
