from .word import Word

CORE : dict[str, Word] = {
    "DROP" : Word("DROP", asm="drop", xt = "xt_drop"),
    "DUP" : Word("DUP", asm="dup", xt = "xt_dup"),
    "SWAP": Word("SWAP", asm = "swap", xt = "xt_swap"),
    "OVER": Word("OVER", asm = "over", xt = "xt_over"),
    "+": Word("+", asm = "add", xt = "xt_add"),
    "1+": Word("1+", asm = "inc", xt = "xt_inc"),
    "1-": Word("1-", asm = "dec", xt = "xt_dec"),
    "-": Word("-", asm = "sub", xt = "xt_sub"),
    "LSHIFT": Word("LSHIFT", asm = "shl", xt = "xt_shl"),
    "RSHIFT": Word("RSHIFT", asm = "shr", xt = "xt_shr"),
    "AND": Word("AND", asm = "and", xt = "xt_and"),
    "OR": Word("OR", asm = "or", xt = "xt_or"),
    "XOR": Word("XOR", asm = "xor", xt = "xt_xor"),
    "INVERT": Word("INVERT", asm = "jal xt_eq0", xt = "xt_eq0"),
    "NOT": Word("NOT", asm = "jal xt_eq0", xt = "xt_eq0"),
    "0=": Word("0=", asm = "jal xt_eq0", xt = "xt_eq0"),
    "0<": Word("0<", asm = "jal xt_lt0", xt = "xt_lt0"),
    "=": Word("=", asm = "jal xt_eq", xt = "xt_eq"),
    "<": Word("<", asm = "jal xt_lt", xt = "xt_lt"),
    ">": Word(">", asm = "jal xt_gt", xt = "xt_gt"),
    "@": Word("@", asm = "jal xt_fetch", xt = "xt_fetch"),
    "!": Word("!", asm = "jal xt_store", xt = "xt_store"),
    "KEY": Word("KEY", asm = "jal xt_key", xt = "xt_key"),
    "EMIT": Word("EMIT", asm = "jal xt_emit", xt = "xt_emit"),
    ">R": Word(">R", asm = "movR", xt = "xt_movR"),
    "R>": Word("R>", asm = "pullR", xt = "xt_pullR"),
    "R@": Word("R@", asm = "copyR", xt = "xt_copyR"),
    "DEPTH": Word("DEPTH", asm = "depth", xt = "xt_depth"),
    "FAIL": Word("FAIL", asm = "ldi 0xff\ntaf", xt = "xt_fail"),
    "CELLS": Word("CELLS", asm = "", xt = ""),
    "ALLOT": Word("ALLOT", asm = "", xt = ""),
}
